### ISSUE TITLE
Remove deprecation warning (will stop working in Python 3.8)

### ISSUE THREAD

**Issue by luizirber** [dib-lab/screed#79]
```
screed/openscreed.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
```

**Comment by mandel01** [comment]
Hi @luizirber, I tried to address the issue with [this commit](https://github.com/mandel01/screed/commit/f5950caccd698b201a68297b8e2f406634a83cb1). It passes the tests on my local machine (python3.7). [On TravisCI, the python2.7 build worked, but the python3.5 build failed](https://travis-ci.org/mandel01/screed/builds/492936732). I think this is an issue with tox or the .travis.yml setup but I wasn't sure. Should I suggest this as a PR, or should I dig further into the TravisCI issue first?

**Comment by luizirber** [comment]
Hi @mandel01! It's ready for opening a PR, I'll fix the Travis config in another PR.

Thanks for fixing it!
